{{- $appName := .Values.labels.appname -}}
{{- $creds := .Values.elasticsearch -}}


apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $appName }}-pipeline-configmap
  labels:
    app: {{ $appName }}-pipeline-configmap
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  logstash.conf: |
    # Sample Logstash configuration for creating a simple
    # Beats -> Logstash -> Elasticsearch pipeline.


    input {
      beats {
       client_inactivity_timeout => 3000
       port => 5044
       ssl  => false
       #codec => "json"
       #include_codec_tag => false
            }
      
          }
          
    filter {

      mutate {
        gsub => [
               "message", '=>', ':'
             #  "message", ':,', ':[],'
               ]
    }
    
    json {
           source => "message"  
         }
    
    }

    output {
      elasticsearch {
       hosts => ["{{ $creds.hosts }}"]
       index => "{{ $creds.index }}"
       user =>  "{{ $creds.username }}"
       password => "{{ $creds.password }}"
       cacert => [ "/usr/share/logstash/pipeline/certificate.pem" ]
       ssl => true
      #  codec => "json"
    } 
  
    stdout {
      codec => json
      }
    }
