apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-prospectors
  namespace: kube-system
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  kubernetes.yml: |-
    - type: log
      paths:
        - /var/lib/docker/containers/*/*.log
        - /var/data/kubeletlogs/*/*/*.log#
      json.message_key: log
      json.keys_under_root: true
      logging.files.keepfiles: 7
      fields:
        clustername: {{ .Values.clustername }}
      fields_under_root: true
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
            namespace: ${POD_NAMESPACE}
